# Generated by Django 3.1.1 on 2020-10-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20201008_1541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
