# Generated by Django 3.1.1 on 2020-10-12 16:27

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('slide', models.FileField(db_column='slide', upload_to=lms.models.upload_location_for_file)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.DO_NOTHING, to='lms.course')),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
    ]
