# Generated by Django 3.1.1 on 2020-10-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
