# Generated by Django 3.1.1 on 2020-10-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20201012_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'managed': False},
        ),
    ]
