# Generated by Django 3.1.1 on 2020-10-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_assignment_learn_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learn',
        ),
    ]
