# Generated by Django 3.1.1 on 2020-10-14 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_delete_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField(db_column='question')),
                ('starttime', models.DateTimeField(db_column='starttime', default=datetime.datetime.now)),
                ('endtime', models.DateTimeField(db_column='endtime')),
                ('finished', models.BooleanField(db_column='finished', default=False)),
            ],
            options={
                'db_table': 'quiz',
                'managed': False,
            },
        ),
    ]
