# Generated by Django 3.1.1 on 2020-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'teach',
                'managed': False,
            },
        ),
    ]
