# Generated by Django 3.1.1 on 2020-12-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_teach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
